-- Generated by nwg-displays on 2026-05-19 at 22:35:45. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.01",
    position = "1920x0",
    scale = 1.5
})
hl.monitor({
    output = "HDMI-A-2",
    mode = "1920x1080@74.97",
    position = "0x0",
    scale = 1.0
})
