-- Generated by nwg-displays on 2026-05-19 at 22:34:12. Do not edit manually.

hl.workspace_rule({
    workspace = "1",
    monitor = "HDMI-A-2",
    default = true
})
hl.workspace_rule({
    workspace = "2",
    monitor = "HDMI-A-2"
})
hl.workspace_rule({
    workspace = "3",
    monitor = "HDMI-A-2"
})
hl.workspace_rule({
    workspace = "4",
    monitor = "HDMI-A-2"
})
hl.workspace_rule({
    workspace = "5",
    monitor = "HDMI-A-2"
})
hl.workspace_rule({
    workspace = "6",
    monitor = "eDP-1",
    default = true
})
hl.workspace_rule({
    workspace = "7",
    monitor = "eDP-1"
})
hl.workspace_rule({
    workspace = "8",
    monitor = "eDP-1"
})
hl.workspace_rule({
    workspace = "9",
    monitor = "eDP-1"
})
hl.workspace_rule({
    workspace = "10",
    monitor = "eDP-1"
})
